### ISSUE TITLE
Does not support `sorting_strategy="descending"`

### ISSUE THREAD

**Issue by otavioschwanck** [fdschmidt93/telescope-egrepify.nvim#10]
![image](https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/9551316/61808691-bcab-4fe4-bd3a-38950b5b1a58)

Handbook has no items, the first item (top from bottom) has no title.

**Comment by fdschmidt93** [comment]
I unfortunately do not run into this issue and spontaneously cannot think as to why this occurs.

Happy to offer more support with more information, like `minimal_init.lua` and reproduction steps.

See also https://github.com/fdschmidt93/telescope-egrepify.nvim#disclaimer

**Comment by otavioschwanck** [comment]
> I unfortunately do not run into this issue and spontaneously cannot think of as to why this occurs.
> 
> Happy to offer more support with more information, like `minimal_init.lua` and reproduction steps.
> 
> See also https://github.com/fdschmidt93/telescope-egrepify.nvim#disclaimer

nvim version: 
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

Mac.

Minimal:
```lua
-------------------------------------------------------------------------------
-- Options
-------------------------------------------------------------------------------
vim.opt.number = true
vim.opt.cursorline = true
vim.opt.smartindent = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.laststatus = 3
vim.opt.cmdheight = 0
vim.opt.numberwidth = 4
vim.opt.signcolumn = "yes"

-------------------------------------------------------------------------------
-- Keymap
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-- Bootstrap Package Manager
-------------------------------------------------------------------------------
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	print("Installing 'folke/lazy.nvim'...")
	vim.fn.system({ "git", "clone", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.rtp:prepend(lazypath)

-------------------------------------------------------------------------------
-- Plugins
-------------------------------------------------------------------------------
require("lazy").setup({
	{
		"nvim-telescope/telescope-fzf-native.nvim",
		build = "cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build",
	},
	{
		"fdschmidt93/telescope-egrepify.nvim",
		keys = {
			{ "<C-p>", "<CMD>Telescope egrepify<CR>", mode = { "n", "i", "v" } },
		},
	},
	{
		"nvim-telescope/telescope.nvim",
		dependencies = "nvim-lua/plenary.nvim",
		config = function()
			require("telescope").setup({
				extensions = {

					fzf = {
						fuzzy = true,
						override_generic_sorter = true,
						override_file_sorter = true,
					},
				},
			})

			require("telescope").load_extension("egrepify")
			require("telescope").load_extension("fzf")
		end,
	},
})

```

**Comment by fdschmidt93** [comment]
Thanks!

I guess I see what happens, the rendering is essentially upside down.

The items are not missing, but rather above then below titles.

**Comment by fdschmidt93** [comment]
Not sure when I'd get around to fix this, because it doesn't affect me (and again, referring to disclaimer as per README).

This actually might be surprisingly annoying, since the "title" gets always send first (and for now, always rendered first). The `entry_maker` now would have to cache the title until another title is shown. This may or may not be easy, begs the question how to ensure the final title is shown correctly though (albeit that hardly matters).

**Comment by otavioschwanck** [comment]
> Not sure when I'd get around to fix this, because it doesn't affect me (and again, referring to disclaimer as per README).
> 
> This actually might be surprisingly annoying, since the "title" gets always send first (and for now, always rendered first). The `entry_maker` now would have to cache the title until another title is shown. This may or may not be easy, begs the question how to ensure the final title is shown correctly though (albeit that hardly matters).

is not just revert the list at th eend?

**Comment by fdschmidt93** [comment]
No, entry maker updates streaming input live. Simple reverting entries may or may not work, but as very hacky and not really any more simpler than a robust solution.

I'd kindly ask you to please refrain from low-effort comments. This is an open source project which I offer at best effort, which I have been very transparent about.

**Comment by otavioschwanck** [comment]
> Owner

i will switch the prompt position to top to work with this extension for now.  Leave this issue open, at the weekend i will try to implement, ok?
