### ISSUE TITLE
sometimes the search comes with a lot files without items

### ISSUE THREAD

**Issue by otavioschwanck** [fdschmidt93/telescope-egrepify.nvim#11]
**
![image](https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/9551316/78d8a649-de7f-4c0a-af34-e6f868158300)
**

**Comment by fdschmidt93** [comment]
I unfortunately do not run into this issue and spontaneously cannot also think of as to why this occurs.

Happy to offer more support with more information, like `minimal_init.lua` and reproduction steps.

See also https://github.com/fdschmidt93/telescope-egrepify.nvim#disclaimer

**Comment by otavioschwanck** [comment]
> I unfortunately do not run into this issue and spontaneously cannot think of as to why this occurs.
> 
> Happy to offer more support with more information, like `minimal_init.lua` and reproduction steps.
> 
> See also https://github.com/fdschmidt93/telescope-egrepify.nvim#disclaimer

nvim version: 
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

Mac.

Minimal:
```lua
-------------------------------------------------------------------------------
-- Options
-------------------------------------------------------------------------------
vim.opt.number = true
vim.opt.cursorline = true
vim.opt.smartindent = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.laststatus = 3
vim.opt.cmdheight = 0
vim.opt.numberwidth = 4
vim.opt.signcolumn = "yes"

-------------------------------------------------------------------------------
-- Keymap
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-- Bootstrap Package Manager
-------------------------------------------------------------------------------
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	print("Installing 'folke/lazy.nvim'...")
	vim.fn.system({ "git", "clone", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.rtp:prepend(lazypath)

-------------------------------------------------------------------------------
-- Plugins
-------------------------------------------------------------------------------
require("lazy").setup({
	{
		"nvim-telescope/telescope-fzf-native.nvim",
		build = "cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build",
	},
	{
		"fdschmidt93/telescope-egrepify.nvim",
		keys = {
			{ "<C-p>", "<CMD>Telescope egrepify<CR>", mode = { "n", "i", "v" } },
		},
	},
	{
		"nvim-telescope/telescope.nvim",
		dependencies = "nvim-lua/plenary.nvim",
		config = function()
			require("telescope").setup({
				extensions = {

					fzf = {
						fuzzy = true,
						override_generic_sorter = true,
						override_file_sorter = true,
					},
				},
			})

			require("telescope").load_extension("egrepify")
			require("telescope").load_extension("fzf")
		end,
	},
})

```

**Comment by otavioschwanck** [comment]
The project that im running into the issues: https://github.com/otavioschwanck/mood-nvim

**Comment by fdschmidt93** [comment]
Cannot reproduce with provided info and no idea why that would happen.
A match in `rg` should always have match items, which should then be shown.

I'd require more context.

**Comment by otavioschwanck** [comment]
> Cannot reproduce with provided info and no idea why that would happen. A match in `rg` should always have match items, which should then be shown.
> 
> I'd require more context.

this problem occurs randomly, very rare

**Comment by otavioschwanck** [comment]
this problem only occurred when the sorting is from below to top, i think is related with the other issue, closing here
