### ISSUE TITLE
[Feature Request] Don't include the number of files in the search count

### ISSUE THREAD

**Issue by kyu08** [fdschmidt93/telescope-egrepify.nvim#24]
Thank you for developing this wonderful extension! I have been using it every day instead of telescope's live_grep since I came across this extension.

## **Is your feature request related to a problem? Please describe.**
Thank you for developing this wonderful extension. I have been using it every day instead of telescope's live_grep since I came across this extention.

## **Describe the solution you'd like**
I would like to suggest that the number of search results should only show the number of matches (as it currently shows the number of matches + number of files). 
Or is it possible to display somewhere the number of files matched or the number of matches? (like `Results (4)` for example)
I am not familiar with telescope's extensions, so maybe this is an impossible request. Also, if this is the intended specification, please feel free to close this issue.

## **Additional context**
<img width="738" alt="image" src="https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/49891479/1deae781-a17b-47e5-83c2-6ee062333c4d">

**Comment by fdschmidt93** [comment]
> Thank you for developing this wonderful extension! I have been using it every day instead of telescope's live_grep since I came across this extension.

Thank you for the kind words :) glad you enjoy the extension!

Your feature request is very sensible, I will hopefully have some time to look into it next week.

**Comment by fdschmidt93** [comment]
The issue should now be fixed, I accidentally pushed it right to `master` rather than a feature branch :sweat_smile: but it should work all the same :)

**Comment by kyu08** [comment]
@fdschmidt93 
Thanks so much for the quick fix.

> I accidentally pushed it right to master rather than a feature branch 😅 

I make the same mistake sometimes when I'm doing personal development projects too. haha

I've actually tried it and I'm so glad it's more convenient!
Thank you so much!

<img width="892" alt="image" src="https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/49891479/65cddf87-65e4-460f-a859-a5b9184cf9b3">
