### ISSUE TITLE
bug: Display `^M` at end of lines on windows.

### ISSUE THREAD

**Issue by mrbeardad** [fdschmidt93/telescope-egrepify.nvim#30]
### Description

![image](https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/54128430/66fdc21e-cefb-4ac7-b4db-909e05dbe9d6)

### Neovim version

```markdown
NVIM v0.10.0-dev-1911+g104565909
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
```

### Operating system and version

Windows 11

### Steps to reproduce

1. `nvim`
2. `:Telescope egrepify`

### Expected behavior

No `^M` at end of lines. Maybe it's due to LF or CRLF

### Actual behavior

All the results with end with `^M`

### Minimal config

```Lua
none
```

**Comment by fdschmidt93** [comment]
Lacks minimal init lua.
