### ISSUE TITLE
Allow possibility to remove default mappings

### ISSUE THREAD

**Issue by jsongerber** [fdschmidt93/telescope-egrepify.nvim#37]
**Is your feature request related to a problem? Please describe.**
The default mappings provided by the extensions prevent using the register in insert mode (\<C-r>), I tried to change the mapping of `toggle_permutations`, but the default still exists, so when I `<C-r>+0` it just insert 0.

**Describe the solution you'd like**
Maybe add a config to disable the default mapping, or only map what's has not be set in config by the user

**Describe alternatives you've considered**
I tried to provide my own keymap in the config, but that didn't remove the default ones.

If you think that's a bug, I can provide a PR this weekend, you just need to tell me what you think would be the better solution, I think a `set_kemap` config option with a default to `true` would prevent breaking changes and fix this issue

**Comment by fdschmidt93** [comment]
This is already possible but somewhat convoluted and probably hidden somewhere in telescope docs.

In your telescope & telescope-egrepify config (cf. README)

```lua
      extensions = {
        egrepify = {
          mappings = {
            ["i"] = {
              ["<C-r>"] = false
            }
          }
        },
       }
```

fixed the issue for me as far as I can tell. Hope that works for you just as well. 
Closing for now, let me know if you have further questions!

**Comment by mrbeardad** [comment]
This does not work now.

**Comment by mrbeardad** [comment]
ok, it is requires `<C-a>` instead of `<C-A>`
