### ISSUE TITLE
Can we support the use of regular expressions for custom AND settings?

### ISSUE THREAD

**Issue by MaJinjie** [fdschmidt93/telescope-egrepify.nvim#44]
**Is your feature request related to a problem? Please describe.**
If support has already been provided, please turn it off

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fdschmidt93** [comment]
Closing since it is an extremely lazy feature request. Plus

Disclaimer on README.

> Please consider forking for your own customization or well-formed PRs instead to fix issues or add new features. This extension foremost serves my own needs and turned into a plugin as maybe other users may want to personalize rg via telescope.nvim in similar fashion. Many options are configurable, but I would like to avoid added maintenace burden beyond review (and hopefully merging) of PRs.
