### ISSUE TITLE
[Help] Search current file

### ISSUE THREAD

**Issue by Ajaymamtora** [fdschmidt93/telescope-egrepify.nvim#51]
Is it possible to search the current file properly? I've tried:
    local current_file = vim.fn.expand "%:p"
    opts.search_dirs = { current_file }

But the previewer breaks (it does just search the current file)

![image](https://github.com/user-attachments/assets/4837bb3e-5902-498c-8f03-92b7da7ba3a7)

**Comment by damanis** [comment]
@Ajaymamtora 
`lua require "telescope".extensions.egrepify.egrepify {search_dirs = { vim.fn.expand "%:p" }, searches_dirs = true}` open proper egrepify window, but pressing <Enter> on some result opens new empty buffer (with name same as current buffer).
